### ISSUE TITLE
Alternative typeclass/overload convention

### ISSUE THREAD

**Issue by mausch** [gmpl/FsControl#17]
In [Fleece](https://github.com/mausch/Fleece) I started with the usual typeclass pattern  used in FsControl, then I [switched to a more ad-hoc pattern](https://github.com/mausch/Fleece/commit/a500c3a9e6163e08f352521c4c062a4153d9ea54).

I'm not sure if the simplification I was able to make, e.g.

```fsharp
static member instance (ToJSON, x: bool, _:JsonValue) = fun () -> JBool x
```
to
```fsharp
static member ToJSON (x: bool) = JBool x
```

came from the ad-hoc inline "instance" or my own misunderstanding of the static type resolution mechanism.

Another benefit of this approach is that Visual Studio is more explicit about the requirements of an inline function. For example hovering over the [roundtrip](https://github.com/mausch/Fleece/blob/master/Tests/Tests.fs#L171) function, VS says "requires member ToJSON and member FromJSON and equality". With the usual approach it would say "requires member instance and member instance and equality".

The downsides I see are:

1. In the example above, if you mistype "ToJSON" the compiler won't find the overload, without any warnings. Then again, if you write "istance" instead of "instance" you have the same problem.
1. Default instances would still require an additional parameter in order to do the inheritance thing.
1. Can't use the generic "Inline.instance", instead the static method lookup has to be embedded for each overloaded function.

What do you think? Do you see any other pros/cons?

**Comment by gmpl** [comment]
I just I realised there is a another good point in the convention you use in Fleece: it doesn't require FsControl at all ! by using values from FsControl as first argument you need to include FsControl always with your library, but in your case you use FsControl because you really want to use the generic functions. That's a very important point.
The other point in addition to the quick intellisense message is that the static member looks "clean", however in the case of FromJSON still there is some noise (an unused parameter and a unit-lambda), anyway is much cleaner than the signatures I have in FsControl. This is something I wasn't very convinced since I started this project, I would like to have clean signatures like your ToJSON. I will start researching for a good compromise between both techniques.

**Comment by gmpl** [comment]
Here is a list of the main things I changed:

 - The method name now is the method name. This is reflected in intellisense and it really helped me to quick spot problems based on the inferred types.
 - The instance parameter now is the last parameter, before it was the first. This makes more sense since the least important parameters comes last, before it was more important because it defined the 'name' of the method.
 - The instance parameter is not used when it's known in advance that the method will not have any default, for example <code>Mappend</code>
- Both the instance and the output parameter (when used) are marked as Optional, unfortunately in F# this has no effect but in other languages it does, anyway ...
- A clean signature is used for 'external' types which ideally is the same signature without the optional parameters. This requires an addition 'defaultN' overload in the TypeMethod definition. In cases where there are no optionals then that overload of course is not needed.
- Clean signature doesn't require FsControl linked at all and I think this is also true for the standard signature, in case it's used in the external 'type'. You can just specify an unbounded generic parameter <code>_</code> I mean without specifying its type and it will resolve as well.
- Tupled methods are preferred. There is no way to call curried methods except they are implemented with lambdas which makes the signature a bit cumbersome. Tupled methods on the other hand are everywhere in the framework and are for instance C# friendly.
- The call of the polymorphic function in a bit more complicated than before but this is encapsulated and centralized in the definition in a method called <code>Invoke</code>

I hope all these breaking changes make sense. It definitely complicated a bit the call of the polymorphic function but all the other benefits worth it, specially because the main focus of this library now is clear that is to 1) use the generic functionality and 2) define your own classes implementing the methods, all this in a friendly way.

I'm using FsControl in another project I have which makes also use of FParsec. What I did is a simple wrapper for [FParsec](https://github.com/gmpl/Bitpart/blob/master/Bitpart/FsParsec.fs) so I don't have duplicate combinators like <code> >>= </code> and <code> |>> </code> (map). This I think is a good compromise for the problem of the orphan instances.

All these breaking changes will be in the coming release of FsControl 2.0

I'm closing this issue now but as any other issue feel free to continue the discussion or to re-open it.
