### ISSUE TITLE
Traversing infinite sequences

### ISSUE THREAD

**Issue by mausch** [gmpl/FsControl#26]
Traversing an infinite list works fine in Haskell: http://ideone.com/GuytMd
But the equivalent F# + FSharpPlus code doesn't terminate and eats infinite memory:

``` fsharp
let x = traverse (fun x -> if x > 4 then Some x else None) (Seq.initInfinite id)
```

This is probably because [foldr is currently strict for seq](https://github.com/gmpl/FsControl/blob/master/FsControl.Core/Foldable.fs#L21)

Maybe a specialized foldr would work here, e.g. http://fpish.net/blog/anton.tayanovskyy/id/1453/http~3a~2f~2fwww.intellifactory.com~2fblogs~2fanton.tayanovskyy~2f2009~2f12~2f11~2fFoldr-or-FoldBack-on-Infinite-F~21sharp~21-Sequences.article

(BTW [this stackoverflow question](http://stackoverflow.com/q/23098484/21239) made me realize this).

**Comment by gmpl** [comment]
The poor man solution seems to be the way to approach this problem.
Each time an optimized or a lazy version is needed a specific instance should be added.
I would say there will be more cases like this, in which the lazyness is not the default since it will not be automatically derived, see for instance the new ``Delay`` method for workflows.

**Comment by gusty** [comment]
This issue was moved to gmpl/FSharpPlus#41
