### ISSUE TITLE
error FS0192 : internal error : GenUnionRef m 

### ISSUE THREAD

**Issue by ctaggart** [gmpl/FsControl#38]
If I upgrade from `1.0.9` to `1.0.10`, the F# Compiler (fsc.exe) from 3.1.2 crashes with an internal error complaining with:
error FS0192 : internal error : GenUnionRef m 

This is a dependency of Fleece. For now, I've locked us down to version `1.0.9`.

**Comment by gmpl** [comment]
Are you updating the FsControl.Core.dll of Fleece binaries without recompiling Fleece?

If so that's very likely to break because there is a lot of code that get inlined at the call site, in this case it will be in Fleece binaries.

I didn't test that scenario but I guess it might work if the changes in FsControl are really minor changes which is not the case at this stage.

You can try recompiling Fleece with the latest version of FsControl, but I would advise to stick to version 1.0.9 as long as you don't need features from newer versions of FsControl.

Also note that Fleece uses also FSharpPlus which is still not upgraded to support FsControl higher that 1.0.9

**Comment by ctaggart** [comment]
Here are the relevant dependencies from `paket.lock`. FSharpPlus isn't locked on a specific version of FsControl. Are you saying that it should be?
```
    Fleece (0.4.0)
      FSharpPlus (>= 0.0.4)
      ReadOnlyCollectionExtensions (>= 1.2.0)
      ReadOnlyCollectionInterfaces (1.0.0)
      System.Json (>= 4.0.20126.16343)

    FSharpPlus (0.0.4)
      FsControl (>= 1.0.9)

    FsControl (1.0.9)
```

**Comment by gmpl** [comment]
I think so. Fleece and FSharpPlus should be locked to a specific version of FsControl. At least during this stage because I'm doing small breaking changes in FsControl.
I should increase the version number to 1.1.x that's my fault, will proceed that way from now on that I know otherwise will be breaking someone else work. Thanks for your feedback.

**Comment by richard-green** [comment]
+1 same issue. reverted to 1.0.9.

**Comment by gmpl** [comment]
Thanks Richard.
I can hide from NUGET all 1.x.x versions greater than 1.0.9 what do you think?

**Comment by gmpl** [comment]
Versions after 1.0.9 are hidden. From now on I will try to respect the versioning system so all breaking changes I'm doing will be for version 2.x.x
