### ISSUE TITLE
The description requires a rewrite or clarification

### ISSUE THREAD

**Issue by gdennie** [gmpl/FsControl#49]
I believe the documentation can be written so that it makes sense to me. Perhaps I am naive. Presently I have no idea what the second paragraph is saying or many subsequent to it (I gave up). I will now turn to the code for an introduction to this library.

**Comment by gmpl** [comment]
Thanks for your feedback. I think it's a valid point, perhaps I can add an example along with the explanation to illustrate what the doc is saying.

**Comment by gdennie** [comment]
I read further to the mention of blogs posts on this subject. A list of links to a few would be helpful.

However, immediately, the following does not make sense to me. Perhaps because it is too dense (or I'm too dumb :) ):

"The goal is to create overloads of standard F# types, organized into types with a single method (Type-Method) to be used from other projects/libraries."

The term, "overloads of standard F# types", does not make sense. Specifically, what does an overloaded "type" look like and why would you overload it? Now, overload methods sounds reasonable per OO frameworks in .Net and Java.

I took a look at some of the code and it appears that FsControl is at least also a collection of type extensions. I am now presuming that "extensions" is what you mean by "overloads". Overloads, I think, is the wrong word here.

**Comment by gmpl** [comment]
Well, in fact it's not that kind of ad-hoc overload you find typically in .NET or Java OOP code. It is more like Haskell's typeclasses, but you shouldn't be familiar with typeclasses to use this library, that's why I think you are right about the docs. Right now they explain the whole thing from scratch but assuming you are familiar with typeclasses I will definitely change that in the docs.

If that's not clear going to read the code will only make the things worse. I would recommend instead to try to follow the sample files, you can download the nuget and the run the scripts. I'm thinking I can add a sample file called getting started with an example of a generic function <code>map</code> so first I show how it works for standard .NET types, then create a custom type Tree and add a method for map, so then the former map function will work also on that type Tree.

The goal is not to create extension methods, that's only an additional thing that might be useful in some cases, indeed those extensions will be added in version 2.0.

It will be interesting to have your feedback again once I update the docs and the sample files.

**Comment by gdennie** [comment]
:)

**Comment by gmpl** [comment]
I just did an update, have a look and give me your feedback.

**Comment by gdennie** [comment]
It is much better. Great job. Will have to spend more time reviewing it. Here is my nit picks so far :) ...

I would change the following...
    static member Map (x:MyFunctor<'T>, f:'T->'U) = {your map impl.} : MyFunctor<'U>

...to this because it fits more useful information in
    static member Map (x:MyFunctor<'T>, f:'T->'U) : MyFunctor<'U> = ...

I am wondering whether static type member constraints could be use to implement this functionality as well. A type would then become available to such a method by merely possessing a method of a suitable signature and perhaps name.

In writing this just now I am realizing a little confusion with typical FP standalone or module bound methods vs OO object bound methods (as supported by the extension syntax). Is FsControl attempting to provide FP functions to an OO context or provide Haskell functionality to an FP oriented F# world. Specifically, the occurrence of the `MyFunctor<'T>` in Map above would normally be the last parameter, not the first.

**Comment by gmpl** [comment]
Thanks, I agree with your suggestion, looks nicer. If you update it I will accept your pull request and you may close the issue if you feel so, anyway we can continue the discussion.

Regarding static member constraints, indeed they are the key feature (together with overloads) that makes FsControl's "magic" possible.

It's more your last sentence, "provide Haskell functionality to an FP oriented F# world" what describe better this project. Methods are been used because it's the only way to provide overloading. Overloading functions (created in modules) directly would only be possible using a "hidden" feature of the F# compiler called Static Optimizations but unfortunately it's intentionally disabled outside the F# compiler itself.

As said before, extension methods are just a "side functionality" of this project, in the rare case you want to reuse some implementations in C# or in F# without generic code inlining. They also allow to use some functions [as operators](https://github.com/gmpl/FsControl/blob/master/FsControl.Core/Samples/Functions.fsx#L61) as in the case of <code>Mappend</code>.

The reason why the functor is the first parameter is purely technical, it behaves better than the opposite when type inference solves constraints. Also note that some methods (not functions) in F# core lib follow that order e.g. <code>async.Bind(x,f)</code> but when you create the generic functions you can swap the parameters which makes more sense since it will allow currying and piping to be coded in a natural way.

**Comment by gdennie** [comment]
So, as I understand it, FsControl uses the OO method overloading feature of .Net static class methods to implement extension methods to provide a particular set of idiomatic Haskell generic functions. 

These functions are generic in that they accept arbitrary types in that they require that they merely implement specific method signatures similar to how Haskell's `Typeclass` constraints work.  These generic functions can also be invoked as standalone function in that they will not need to have their implementation prefix once their defining module is in scope because...the generic function, through the use of the inline function `FsControl.Core.TypeMethods._.Invoke` and method overloading, becomes merely a type inferencing redirection mechanism to produce an implementation bounded type at compile time.

...This is a stab at my summary to date. Whether I am right or wrong, it is brilliant none the less :)

**Comment by gmpl** [comment]
Yes, you're interpretation is correct. Keep in mind that is INSPIRED in Haskell, because there are some differences, in that some abstractions were adapted to match F# standards. Also there are some generic functions that don't exist in Haskell, those in the Collection.fs file for instance.

**Comment by gdennie** [comment]
It would seem there are two distinct innovations here. The first is the compile time binding that allows for standalone function syntax. The second is the actually implementation of the Haskell inspired functionality. Specifically, the notion of map without the need to stipulate the module of List, Array, or Seq, etc. would seem to be a significant enhancement worthy of incorporation into the core language itself.

**Comment by gmpl** [comment]
Yes, anyway at the time of starting this library there were already other projects porting ideas from Haskell, like [FParsec](http://www.quanttec.com/fparsec/), FsCheck, FSharpx to name some of them, but none with this kind of generic functionality.

Here's the long story:

I discovered this possibility some years ago while playing with [generic tuple functions](http://nut-cracker.azurewebsites.net/blog/2011/11/07/functions-for-n-tuples/) since then I refined this technique, toyed with a [Haskell Compatibility library](https://code.google.com/p/fsharp-typeclasses/), received some positive (and negative) feedback, valuable suggestions and the idea of doing an F# specific library came up. 

By that time [F#x](http://bugsquash.blogspot.fr/2011/10/introducing-fsharpx.html) was in early stages and getting some popularity, trying to offer the same abstractions but failing to do it in a generic way. 
So we tried to merge my project there but there was no general consensus about this and finally [my pull request](https://github.com/fsprojects/FSharpx.Extras/pull/24) got declined.

So I decided to start this project, and another one called [F#+](https://github.com/gmpl/FSharpPlus) which offers some collections already defined in F#x. Anyway the idea is not to compete with other libraries, that makes no sense to me, on the contrary I want to offer the possibility to integrate it with as many other libraries as possible but this is not always doable, specifically when the library implements most functions as function values in modules instead of static members of the type itself.
Unfortunately this is the case in most F#x collections. Also FParsec presents a problem to integrate with, since it uses a type alias for function application, so in one of my projects what I did is to write a [wrapper](https://github.com/gmpl/Bitpart/blob/master/Bitpart/FsParsec.fs).

Nowadays I find this library very useful for my day to day coding and I think that by sharing it might receive valuable contributions and we all can benefit from it.

**Comment by gdennie** [comment]
Interesting. I am glad you persevered. I can appreciate why some would spurn the use of static class methods and other object oriented paraphernalia. However, clearly your approach seem to have hit the proverbial nail on the head. It would appear to have embrace all the efficiency of dedicated implementations while maintaining the flexibility and reliability to type inference. The ability to embrace Typeclass style coding in F# is welcomed. Thanks again.
