### ISSUE TITLE
A name that markets it better to F# users.

### ISSUE THREAD

**Issue by EricGT** [gmpl/FsControl#63]
I left a comment on StackOverflow:

> In the last few days I ran into references for FsControl a few times so I finally stated looking at it closely and like what I see. If you had only given it a better name I might have been using it for a few years now. Every time I saw FsControl I would think Windows Form controls and say, I don't need this. I give it vote to have a name change. :) 

and received:

> I agree. Control comes from the Haskell libraries that inspired the project but I would be happy to put a better name, I invite you to open an issue suggesting a name change. – Gustavo

I don't have any ideas for a better name at present, but firmly believe that people using F# should be aware of this. In reading the examples some of the fog (no pun intended) I had with F# started to disappear.

**Comment by gmpl** [comment]
I think it's a good thing to do some marketing to F# user about this library, it wasn't a priority at the beginning but now that it has reached a mature version it would be a good thing in order to get more feedback and contributions.
Changing the name may help, also documenting, adding sample code and blogging.
Remember that this project is a base library, whereas FSharpPlus intention is to go further and provide additional types (that's why it has a plus).
So here the name should be related to a core library which uses a static method convention for ad-hoc polymorphism.
If someone has better names in mind please post them.

**Comment by gmpl** [comment]
If we decide to go ahead with #71 we'll be also solving the issue of the project name. I think F#+ would market better ;)

**Comment by gusty** [comment]
#71 was implemented. Hopefully it markets better, not just because of the name, also by the fact that it offers more functionalities and less dependencies.
