### ISSUE TITLE
No Comonad for Options?

### ISSUE THREAD

**Issue by robkuz** [gmpl/FsControl#65]
There is no definition for a Comonad for Options which is a Monad and therefore should have a Comonad, No?

**Comment by gmpl** [comment]
No, not all monads are comonads. Even <code>List</code> is not a proper comonad since the list can be empty. 
I'm not sure if there is a rule but I think that a Monad can be made either a Monad Plus or a Comonad, but not both at the same time.
As an example a [non-empty list](https://github.com/gmpl/FSharpPlus/blob/ad2bf4d74750a4e4bac81642338e7553c41ced14/FSharpPlus/NonEmptyList.fs#L47-L49) is not a monad plus since it has no ZERO but can be a comonad, the opposite is true for a normal list.
List, Array and Seq are there as [restricted comonads](https://github.com/gmpl/FsControl/blob/a55d21b355c537960aaf0677be4bc36095a9c312/FsControl.Core/Functor.fs#L349) since it lacks the extract operation which would not be a total function, anyway it might be [interesting to be able to generalize](https://github.com/gmpl/FsControl/issues/40) on the other operations.
