### ISSUE TITLE
Usage of FsControl makes VSCode + Ionide slow

### ISSUE THREAD

**Issue by robkuz** [gmpl/FsControl#66]
Just a subjective observation.
Since I switched to FsControl and the usage of its operators Ionide tooltips and code suggestions have become pretty slow.

**Comment by gmpl** [comment]
Your observation is not that subjective, it is slow since it relies in overload resolution which in the current version of F# is really slow.
Here's a proposal to [make it faster](https://github.com/Microsoft/visualfsharp/pull/1530), hopefully it will be accepted for F# 4.1
So this is in fact an [F# compiler issue](https://github.com/Microsoft/visualfsharp/issues/343).

**Comment by robkuz** [comment]
interesting. I hope your PR will be merged and I only have to wait for V 4.1 and the mono binary drop. Can only be a few more month ;-)

**Comment by gmpl** [comment]
@robkuz it was just merged today :)
